# Generated by Django 5.0.6 on 2024-10-13 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_userregistration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
